/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContributionRouteImport } from './routes/contribution'
import { Route as EcheancesRouteImport } from './routes/echeances'
import { Route as ImpotRouteImport } from './routes/impot'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as FacturesIndexRouteImport } from './routes/factures.index'
import { Route as FacturesIdRouteImport } from './routes/factures.$id'
import { Route as FacturesNouvelleRouteImport } from './routes/factures.nouvelle'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as FacturesIdModifierRouteImport } from './routes/factures_.$id.modifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributionRoute = ContributionRouteImport.update({
  id: '/contribution',
  path: '/contribution',
  getParentRoute: () => rootRouteImport,
} as any)
const EcheancesRoute = EcheancesRouteImport.update({
  id: '/echeances',
  path: '/echeances',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpotRoute = ImpotRouteImport.update({
  id: '/impot',
  path: '/impot',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIndexRoute = FacturesIndexRouteImport.update({
  id: '/factures/',
  path: '/factures/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIdRoute = FacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesNouvelleRoute = FacturesNouvelleRouteImport.update({
  id: '/factures/nouvelle',
  path: '/factures/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/admin/utilisateurs',
    path: '/admin/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const FacturesIdModifierRoute = FacturesIdModifierRouteImport.update({
  id: '/factures_/$id/modifier',
  path: '/factures/$id/modifier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contribution': typeof ContributionRoute
  '/echeances': typeof EcheancesRoute
  '/impot': typeof ImpotRoute
  '/profil': typeof ProfilRoute
  '/factures/$id': typeof FacturesIdRoute
  '/factures/nouvelle': typeof FacturesNouvelleRoute
  '/factures/': typeof FacturesIndexRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/factures/$id/modifier': typeof FacturesIdModifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contribution': typeof ContributionRoute
  '/echeances': typeof EcheancesRoute
  '/impot': typeof ImpotRoute
  '/profil': typeof ProfilRoute
  '/factures/$id': typeof FacturesIdRoute
  '/factures/nouvelle': typeof FacturesNouvelleRoute
  '/factures': typeof FacturesIndexRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/factures/$id/modifier': typeof FacturesIdModifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contribution': typeof ContributionRoute
  '/echeances': typeof EcheancesRoute
  '/impot': typeof ImpotRoute
  '/profil': typeof ProfilRoute
  '/factures/$id': typeof FacturesIdRoute
  '/factures/nouvelle': typeof FacturesNouvelleRoute
  '/factures/': typeof FacturesIndexRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/factures_/$id/modifier': typeof FacturesIdModifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contribution'
    | '/echeances'
    | '/impot'
    | '/profil'
    | '/factures/$id'
    | '/factures/nouvelle'
    | '/factures/'
    | '/admin/utilisateurs'
    | '/factures/$id/modifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contribution'
    | '/echeances'
    | '/impot'
    | '/profil'
    | '/factures/$id'
    | '/factures/nouvelle'
    | '/factures'
    | '/admin/utilisateurs'
    | '/factures/$id/modifier'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contribution'
    | '/echeances'
    | '/impot'
    | '/profil'
    | '/factures/$id'
    | '/factures/nouvelle'
    | '/factures/'
    | '/_authenticated/admin/utilisateurs'
    | '/factures_/$id/modifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContributionRoute: typeof ContributionRoute
  EcheancesRoute: typeof EcheancesRoute
  ImpotRoute: typeof ImpotRoute
  ProfilRoute: typeof ProfilRoute
  FacturesIdRoute: typeof FacturesIdRoute
  FacturesNouvelleRoute: typeof FacturesNouvelleRoute
  FacturesIndexRoute: typeof FacturesIndexRoute
  FacturesIdModifierRoute: typeof FacturesIdModifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribution': {
      id: '/contribution'
      path: '/contribution'
      fullPath: '/contribution'
      preLoaderRoute: typeof ContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echeances': {
      id: '/echeances'
      path: '/echeances'
      fullPath: '/echeances'
      preLoaderRoute: typeof EcheancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impot': {
      id: '/impot'
      path: '/impot'
      fullPath: '/impot'
      preLoaderRoute: typeof ImpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/': {
      id: '/factures/'
      path: '/factures'
      fullPath: '/factures/'
      preLoaderRoute: typeof FacturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/$id': {
      id: '/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof FacturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/nouvelle': {
      id: '/factures/nouvelle'
      path: '/factures/nouvelle'
      fullPath: '/factures/nouvelle'
      preLoaderRoute: typeof FacturesNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/factures_/$id/modifier': {
      id: '/factures_/$id/modifier'
      path: '/factures/$id/modifier'
      fullPath: '/factures/$id/modifier'
      preLoaderRoute: typeof FacturesIdModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContributionRoute: ContributionRoute,
  EcheancesRoute: EcheancesRoute,
  ImpotRoute: ImpotRoute,
  ProfilRoute: ProfilRoute,
  FacturesIdRoute: FacturesIdRoute,
  FacturesNouvelleRoute: FacturesNouvelleRoute,
  FacturesIndexRoute: FacturesIndexRoute,
  FacturesIdModifierRoute: FacturesIdModifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
